[package]
name = "biograf-rs"
version = "0.0.0"
edition = "2018"
authors = ["Tim Janke <tim+github@janke.biz>"]
description = "A simple helper tool to quickly optimize your YouTube playlists"
repository = "https://github.com/flying7eleven/biograf-rs"
readme = "README.md"
license-file = "LICENSE.md"

[dependencies]
